GET http://localhost:8080/api/orders?month=7
Accept: application/json

###
GET http://localhost:8080/api/orders
Accept: application/json

###
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "productNumber": "CK8987L"
}

###
PUT http://localhost:8080/api/orders/1/shipping
Content-Type: application/json

{
  "shippingPrice": 2000
}